version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: go/src/github.com/pragmader/q3-server-bot
    steps:
      - checkout
      - run: make
      - run: make test
